apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sales-app
  template:
    metadata:
      labels:
        app: sales-app
    spec:
      containers:
      - name: sales-app
        image: 7787073570/my_sales_app:latest
        ports:
        - containerPort: 8080
